<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>00.썸네일</name>
   <tag></tag>
   <elementGuidId>14160bfe-fe2e-4b8a-afa9-b36657d89d40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrap']/div/section/ul/li/div/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.thumb-overlay</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fdbf2a3d-9ecc-4892-b4e8-a406e86c0be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>thumb-overlay</value>
      <webElementGuid>9fdd8b8f-f0f5-4897-80dc-267bb3ee4e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrap&quot;)/div[@class=&quot;global-page&quot;]/section[@class=&quot;page-section&quot;]/ul[@class=&quot;content-list-wrap&quot;]/li[@class=&quot;search-item-wrap&quot;]/div[@class=&quot;item-thumb-wrap&quot;]/a[@class=&quot;thumb-wrap js-fb-tracking js-tiara-tracking&quot;]/div[@class=&quot;thumb-overlay&quot;]</value>
      <webElementGuid>0fa649b9-c416-44eb-80d9-62b8b2c7aa48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrap']/div/section/ul/li/div/a/div</value>
      <webElementGuid>2990565c-9be2-44ee-bc8b-b13d9cab5769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/a/div</value>
      <webElementGuid>e40e7bea-2172-4607-9b1f-0a6a22b4c237</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
