<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>05.댓글버튼</name>
   <tag></tag>
   <elementGuidId>390f89b9-e664-4430-9470-bbb976cf71a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrap']/div/div[5]/div/div[3]/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.toolbar-btn.js-wide-comment-btn.js-comment-btn.js-fb-tracking</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a77e0a0d-9d15-46a7-ac52-b673fc2c6c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toolbar-btn js-wide-comment-btn js-comment-btn js-fb-tracking</value>
      <webElementGuid>196ac92b-5b38-4602-baae-e16ae2df1246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fb-event</name>
      <type>Main</type>
      <value>screen_comment</value>
      <webElementGuid>cec72572-9a4f-4251-a5a3-5aa1d3732a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-episode-id</name>
      <type>Main</type>
      <value>3465298</value>
      <webElementGuid>2e9bc272-8cb9-4014-9ac9-3026dd0fa1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Comment</value>
      <webElementGuid>21441bdc-1129-4ddf-94d8-64491a1e791a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrap&quot;)/div[@class=&quot;vw-root js-viewer-root&quot;]/div[@class=&quot;toolbar&quot;]/div[@class=&quot;toolbar__wrapper toolbar__wrapper--wide js-toolbar&quot;]/div[@class=&quot;toolbar__row toolbar__row--right&quot;]/div[@class=&quot;row-item row-item--toggle js-hide-section&quot;]/div[@class=&quot;toggle-btn toggle-btn--selected&quot;]/a[@class=&quot;toolbar-btn js-wide-comment-btn js-comment-btn js-fb-tracking&quot;]</value>
      <webElementGuid>f24828cb-3744-4989-a46f-f8d9b684e01d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrap']/div/div[5]/div/div[3]/div/div[2]/a</value>
      <webElementGuid>73a1cec5-9655-4831-aed0-f1e7279a0000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List'])[1]/following::a[1]</value>
      <webElementGuid>a59e90b0-7afe-4b6d-894e-b35f2fff77b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support'])[1]/following::a[2]</value>
      <webElementGuid>d7b7341e-554e-4fe8-859e-2d08e8a51e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prev'])[1]/preceding::a[1]</value>
      <webElementGuid>f3ae7ded-e23f-4023-8306-0ae03d933d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[3]/div/div[2]/a</value>
      <webElementGuid>d9b736c2-99ce-4091-97ab-0d535f98a0f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Comment' or . = 'Comment')]</value>
      <webElementGuid>92972016-126c-4c24-9594-f828dba72e2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
