<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>12.댓글수</name>
   <tag></tag>
   <elementGuidId>cfe01531-0940-4788-9587-3ef44186f13a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrap']/div/div[5]/div/div/div/div/p[2]/span[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.comment-stat.js-comment-stat</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f0afa2b7-e2f0-4d2a-8128-ff4b740c1ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>comment-stat js-comment-stat</value>
      <webElementGuid>6c92edfc-a55a-469c-829c-ebc2c21854d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>150 comments</value>
      <webElementGuid>2d57eb18-ca02-49c1-883b-e764ed8c04a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrap&quot;)/div[@class=&quot;vw-root js-viewer-root&quot;]/div[@class=&quot;toolbar&quot;]/div[@class=&quot;toolbar__wrapper toolbar__wrapper--wide js-toolbar&quot;]/div[@class=&quot;toolbar__row toolbar__row--left&quot;]/div[@class=&quot;row-item row-item--info js-toolbar-episode&quot;]/div[@class=&quot;episode-info&quot;]/p[@class=&quot;stat&quot;]/span[@class=&quot;comment-stat js-comment-stat&quot;]</value>
      <webElementGuid>db8471e5-ff84-4c19-884c-d6273ab7c596</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrap']/div/div[5]/div/div/div/div/p[2]/span[5]</value>
      <webElementGuid>482c5bba-2d19-42cf-8d96-0f125eba3829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comment'])[1]/following::span[5]</value>
      <webElementGuid>a380c1a8-92fd-4bfb-bd1c-431de10a5fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More comments'])[1]/following::span[5]</value>
      <webElementGuid>f04130b0-616b-4b7e-b652-762559222974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[3]/preceding::span[1]</value>
      <webElementGuid>3fca0e39-119a-4963-b2f0-7d14a5cc1460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Like'])[1]/preceding::span[2]</value>
      <webElementGuid>d396c101-6d0b-45a6-86a8-0a6644337c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='150 comments']/parent::*</value>
      <webElementGuid>f57bcd08-c83c-495d-a55a-2c0a139478f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]</value>
      <webElementGuid>093836eb-71ee-4b79-8f61-1991b696892d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '150 comments' or . = '150 comments')]</value>
      <webElementGuid>d79473f9-4b94-4bbc-a6e4-3f4a2c2f53fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
