<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>19.전체화면버튼</name>
   <tag></tag>
   <elementGuidId>0bfbad9c-6727-401c-ab38-ed630c5e2f84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrap']/div/div[5]/div/div[3]/div[3]/a/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.ico.sp-ico-full-wht-m</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>34113bcf-7714-4b1b-9030-6bde7edb8731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ico sp-ico-full-wht-m</value>
      <webElementGuid>0428035d-a2d4-48cb-8c35-f006d0fe0efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrap&quot;)/div[@class=&quot;vw-root js-viewer-root&quot;]/div[@class=&quot;toolbar&quot;]/div[@class=&quot;toolbar__wrapper toolbar__wrapper--wide js-toolbar&quot;]/div[@class=&quot;toolbar__row toolbar__row--right&quot;]/div[@class=&quot;row-item&quot;]/a[@class=&quot;toolbar-btn js-full-btn&quot;]/div[@class=&quot;ico-wrap&quot;]/i[@class=&quot;ico sp-ico-full-wht-m&quot;]</value>
      <webElementGuid>c9cec24d-82ec-4c13-8a7b-0d183705a655</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrap']/div/div[5]/div/div[3]/div[3]/a/div/i</value>
      <webElementGuid>9558671c-d547-4abd-87a9-57e9fa5b8c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/div/i</value>
      <webElementGuid>2633ee79-ecc6-47a1-9f4a-045a4b90d9e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
