<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>27.Accept버튼</name>
   <tag></tag>
   <elementGuidId>c8496270-da31-41d8-962c-c0b3ac285b6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gdpr-cookie-accept</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='gdpr-cookie-accept']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>11e6e3b0-2158-4830-8bdd-6a5397300ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gdpr-cookie-accept</value>
      <webElementGuid>8b22547e-5b5b-4614-8198-ee3d12250168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ad2e700f-7ca7-4de9-8ba7-d12f808ae1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accept</value>
      <webElementGuid>d3a1b7b9-0846-4b14-bb7c-ec6c57a15883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gdpr-cookie-accept&quot;)</value>
      <webElementGuid>6706256e-26bd-4892-b53f-63c17b4b034e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='gdpr-cookie-accept']</value>
      <webElementGuid>6970f336-691e-48a2-bbbe-db3e402c338b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cookie-accept-wrapper']/button</value>
      <webElementGuid>1f955fdb-0af6-40e9-ad2e-118cb13d36a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketing'])[1]/following::button[1]</value>
      <webElementGuid>3617a23d-f8cc-43eb-a990-04b787dd09d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Analytics'])[1]/following::button[1]</value>
      <webElementGuid>bb50b4df-90e3-44ea-b52f-66b545804655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accept']/parent::*</value>
      <webElementGuid>7aedc04f-49e4-4012-8400-05db3adc12ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>4469e7df-c440-45a9-9c30-fd6106f9a517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'gdpr-cookie-accept' and @type = 'button' and (text() = 'Accept' or . = 'Accept')]</value>
      <webElementGuid>e3ff61f8-7f25-4901-9f4e-d9534ddf1984</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
