<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>30.플러스 버튼</name>
   <tag></tag>
   <elementGuidId>d351acb9-8286-42e5-8a66-48679a2395b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrap']/div/div[5]/div/div/div[2]/div/div[3]/a[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.sp-viewer-plus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e8250b6a-3f86-4958-8278-5ad08bd697cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sp-viewer-plus</value>
      <webElementGuid>5d640757-403d-4db8-b520-8bb08560b1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrap&quot;)/div[@class=&quot;vw-root js-viewer-root&quot;]/div[@class=&quot;toolbar&quot;]/div[@class=&quot;toolbar__wrapper toolbar__wrapper--wide js-toolbar&quot;]/div[@class=&quot;toolbar__row toolbar__row--left&quot;]/div[@class=&quot;row-item&quot;]/div[@class=&quot;dropdown-float dropdown-float--view js-edit-menu js-float&quot;]/div[@class=&quot;edit__size size--font js-font-size&quot;]/a[@class=&quot;js-plus&quot;]/i[@class=&quot;sp-viewer-plus&quot;]</value>
      <webElementGuid>2c383e14-2fb7-4f5b-bc44-0d7171114f37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrap']/div/div[5]/div/div/div[2]/div/div[3]/a[2]/i</value>
      <webElementGuid>281f63ff-5f57-4f5c-a519-02fabb672147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/a[2]/i</value>
      <webElementGuid>e9a20ae9-3a25-4f1f-8444-81b7a56bb2ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
