<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>35.좌측정렬</name>
   <tag></tag>
   <elementGuidId>d063ee65-fecf-4112-84d6-b5b0c19f05e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrap']/div/div[5]/div/div/div[2]/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.js-align.js-align-left.sp-ico-align-left-qnc-m</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5cf0598d-5d58-44f4-9cc2-be5504365986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-align js-align-left sp-ico-align-left-qnc-m</value>
      <webElementGuid>62701f49-a2be-4993-9b85-6c9e40292844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>469f7b4a-edac-4bb3-8df3-a35e6c35f3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrap&quot;)/div[@class=&quot;vw-root js-viewer-root&quot;]/div[@class=&quot;toolbar&quot;]/div[@class=&quot;toolbar__wrapper toolbar__wrapper--wide js-toolbar&quot;]/div[@class=&quot;toolbar__row toolbar__row--left&quot;]/div[@class=&quot;row-item&quot;]/div[@class=&quot;dropdown-float dropdown-float--view js-edit-menu js-float&quot;]/div[@class=&quot;edit__align&quot;]/a[@class=&quot;js-align js-align-left sp-ico-align-left-qnc-m&quot;]</value>
      <webElementGuid>7ae6541f-268b-41c9-a182-901a78175bb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrap']/div/div[5]/div/div/div[2]/div/div[2]/a</value>
      <webElementGuid>74fea7e5-35a7-44a9-8de8-45525b59541b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div[2]/a</value>
      <webElementGuid>3bb48606-afe7-4e54-bd00-917314050200</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
