<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>40. Support 버튼</name>
   <tag></tag>
   <elementGuidId>134d9363-f0e5-40a5-9621-c2318a8acd79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrap']/div/div[5]/div/div[2]/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7186ddeb-bf67-4a95-badf-99c55939ee8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toolbar-btn js-have-to-sign</value>
      <webElementGuid>d5dcd507-f4dd-4fc6-9968-72c09f0e65fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ga-category</name>
      <type>Main</type>
      <value>Support</value>
      <webElementGuid>1e7ec1aa-be05-43cb-a82a-b9eca09ce977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ga-action</name>
      <type>Main</type>
      <value>Click</value>
      <webElementGuid>b4ea2b45-9af0-441b-95e6-5dd8abc0cd39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ga-label</name>
      <type>Main</type>
      <value>episode_w_tab</value>
      <webElementGuid>c44cb72b-5b8f-4e25-a3ff-5e94c838850a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fb-event</name>
      <type>Main</type>
      <value>screen_support</value>
      <webElementGuid>b45df31f-0c15-41d9-bb30-d319c450c487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-permalink</name>
      <type>Main</type>
      <value>https://tapas.io/series/Soft-Touch</value>
      <webElementGuid>304a0f7e-f4aa-4543-a02c-5504fc510a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-where</name>
      <type>Main</type>
      <value>Episode</value>
      <webElementGuid>ba017526-1b03-4b00-846a-a834ec8f12f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>support</value>
      <webElementGuid>7b07f3d2-a3ed-452d-ba56-c96f52707573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-position</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>30d90cb3-4956-4eae-8a77-4f78fdf82460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-path</name>
      <type>Main</type>
      <value>river_onei</value>
      <webElementGuid>360b42e0-b45e-427b-8a19-983de81e1e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>660Support</value>
      <webElementGuid>da132537-8b8d-4a76-8761-6613fa7bb30b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrap&quot;)/div[@class=&quot;vw-root js-viewer-root&quot;]/div[@class=&quot;toolbar&quot;]/div[@class=&quot;toolbar__wrapper toolbar__wrapper--wide js-toolbar&quot;]/div[@class=&quot;toolbar__row toolbar__row--center&quot;]/div[@class=&quot;row-item&quot;]/a[@class=&quot;toolbar-btn js-have-to-sign&quot;]</value>
      <webElementGuid>73dd2da5-8994-4c9f-9377-602914d2bf56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrap']/div/div[5]/div/div[2]/div/a[2]</value>
      <webElementGuid>9e45b366-b82f-4924-ad4b-929e86086499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Like'])[1]/following::a[1]</value>
      <webElementGuid>f08577b9-81f4-433c-bd70-f67923296035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[3]/following::a[2]</value>
      <webElementGuid>9e01b66b-2269-4a6d-b61a-22775006c8c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List'])[1]/preceding::a[1]</value>
      <webElementGuid>547a7e73-65c4-445a-95a1-e06759afca5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/a[2]</value>
      <webElementGuid>f3ae7d2f-ffca-4230-bcf2-c1d29a6562c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '660Support' or . = '660Support')]</value>
      <webElementGuid>6bac6aa0-5a47-4cfa-a420-08d1a481af0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
