<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>02.Novel버튼</name>
   <tag></tag>
   <elementGuidId>4e02d669-1405-4f2e-a56c-57b76decc634</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/main/section/section/div/div/div/div/div/div/div/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eba8d1d0-0ce1-4713-9376-49fc9e62ac08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group relative mb-4 mr-12 inline-flex h-20 cursor-pointer whitespace-nowrap font-system-14b text-base60 hover:text-base60</value>
      <webElementGuid>8cc7a63e-b224-48a4-80e7-32a32fd20783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/menu/1/subtab/3?category=NOVEL</value>
      <webElementGuid>55696b2f-667a-4b2c-812a-52d4bb826f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Novels</value>
      <webElementGuid>7bd86888-1241-462c-bba9-838275bb7a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative mx-auto flex min-h-full flex-col text-base60 __variable_a04e73 __variable_aa69c3&quot;]/div[@class=&quot;mx-auto flex grow flex-col w-1010&quot;]/main[@class=&quot;flex flex-col items-center w-full space-y-4&quot;]/section[@class=&quot;flex flex-col items-center self-stretch w-full space-y-4&quot;]/section[@class=&quot;w-full&quot;]/div[@class=&quot;flex w-full&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;mb-20 mr-18 flex flex-col&quot;]/div[@class=&quot;flex justify-center&quot;]/div[@class=&quot;relative flex grow flex-col justify-center overflow-x-hidden&quot;]/div[1]/div[@class=&quot;relative&quot;]/div[@class=&quot;z-navigation flex w-full items-center overflow-x-scroll scrollbar-hide&quot;]/a[@class=&quot;group relative mb-4 mr-12 inline-flex h-20 cursor-pointer whitespace-nowrap font-system-14b text-base60 hover:text-base60&quot;]</value>
      <webElementGuid>2758bd63-4c9a-4f08-96a1-c8f31691f4b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/section/section/div/div/div/div/div/div/div/div/a[2]</value>
      <webElementGuid>a29a9b7b-d54f-4499-a973-bfbaa2b85934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Novels')]</value>
      <webElementGuid>9d47ee5e-0bcf-4c00-b18d-0aaee30d2357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comics'])[2]/following::a[1]</value>
      <webElementGuid>6f9c46a2-eba3-4a2a-b021-353ecc5b4d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publish'])[1]/following::a[9]</value>
      <webElementGuid>18abe65c-364f-43eb-8d41-420890349e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UP'])[1]/preceding::a[5]</value>
      <webElementGuid>8f140370-94bf-4702-a61c-529c55bc907b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UP'])[2]/preceding::a[6]</value>
      <webElementGuid>e4bfebaf-8c93-4b1c-84a3-04b6ec5b6923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/menu/1/subtab/3?category=NOVEL')])[2]</value>
      <webElementGuid>dfe473da-fb41-4edb-90ad-593dcfacde9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/a[2]</value>
      <webElementGuid>56462621-18d9-46b0-b0e7-98be56e60e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/menu/1/subtab/3?category=NOVEL' and (text() = 'Novels' or . = 'Novels')]</value>
      <webElementGuid>a140390f-e941-406d-8aa6-260e560a7b7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
