<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>00.로그인버튼</name>
   <tag></tag>
   <elementGuidId>d2435de5-d21d-42bb-9e43-d55a2c291527</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.p-btn.normal.static.js-submit.js-tiara-tracking.quince</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5d12cd9f-cefb-4ad5-aba0-cf5092b35650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6ffce170-8cac-4601-a7ba-0ff0549735d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d22b5d13-9fa2-4d66-a1dd-bbad8424cb1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-btn normal static js-submit js-tiara-tracking quince</value>
      <webElementGuid>1a656638-4444-461c-825b-81f1801cfa02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-section</name>
      <type>Main</type>
      <value>auth</value>
      <webElementGuid>6420cbfd-f6ab-4d22-83ed-fc2ed22432ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-page</name>
      <type>Main</type>
      <value>auth_login</value>
      <webElementGuid>4f03e0bf-25d3-47ee-b50a-3354ebd02e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-action-name</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>c4c6919b-4887-4d9d-a642-f9fcdabbee64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-custom-props-user-action</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>8a3fe6c7-e2e8-42f6-9fe8-1a4b4248df45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log in</value>
      <webElementGuid>8d100589-5b27-4163-aded-500f76a935bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrap&quot;)/div[@class=&quot;global-sign-page&quot;]/div[@class=&quot;global-prompt mod-sign js-sign-page&quot;]/div[@class=&quot;sign-menu mod-effect on js-sign-module js-login&quot;]/div[@class=&quot;sign-button-wrap&quot;]/form[@class=&quot;js-sign-form&quot;]/div[@class=&quot;sign-btn&quot;]/button[@class=&quot;p-btn normal static js-submit js-tiara-tracking quince&quot;]</value>
      <webElementGuid>c40f05a6-79d4-446e-9f8f-525109793064</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>27b7f1f4-9d4f-4621-83ef-29a59e79b7e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrap']/div/div/div/div/form/div[3]/button</value>
      <webElementGuid>3b5e8d4e-9e72-4f5f-9875-21a8b6d14076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password?'])[1]/following::button[1]</value>
      <webElementGuid>b1b7d83d-d18b-4ee3-87bf-c9d6a1bd45fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>5b2c633d-df74-4fd3-829f-2338c953ba04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook or Google'])[1]/preceding::button[1]</value>
      <webElementGuid>d0c7ce6c-13a7-4271-83c0-a4c885739c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in to Tapas'])[1]/preceding::button[1]</value>
      <webElementGuid>6f6f35ef-9b49-49a9-a823-430dc84fcd4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>2fcd2a5e-8b25-477e-8a3e-5db5887fbc75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Log in' or . = 'Log in')]</value>
      <webElementGuid>8b84dcd5-157c-453a-88c2-5864097253ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
