<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>01.아매알압력란</name>
   <tag></tag>
   <elementGuidId>a45811ce-9c1d-484c-893f-5e5308cc54f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'email' and @name = 'email' and @placeholder = 'name@email.com']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a622bf31-9442-44cb-a9cf-1327f5be199b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>50a7b99b-4474-45fb-96d2-6c768007d4d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>083996ec-5ba3-4d38-9ee5-a8efe4d0f778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sign-input-text js-txt js-focus</value>
      <webElementGuid>080b5df9-deb2-4e8f-9dd4-f9c1abcfe22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>name@email.com</value>
      <webElementGuid>166abcbd-e1b0-46bf-a658-2f58ba82ca54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>d1d9a81e-f4f5-41ab-b622-9eff910dbad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2f4cf489-9d1c-43d0-9760-d5065dcde795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrap&quot;)/div[@class=&quot;global-sign-page&quot;]/div[@class=&quot;global-prompt mod-sign js-sign-page&quot;]/div[@class=&quot;sign-menu mod-effect on js-sign-module js-login&quot;]/div[@class=&quot;sign-button-wrap&quot;]/form[@class=&quot;js-sign-form&quot;]/div[@class=&quot;sign-input&quot;]/input[@class=&quot;sign-input-text js-txt js-focus&quot;]</value>
      <webElementGuid>167ee210-647d-44ae-af95-f08cf49bdd72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>c282fa0f-964e-4ce7-b517-9ade5eebd7d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrap']/div/div/div/div/form/div/input</value>
      <webElementGuid>49916c12-74f3-4684-bfe6-25914356da1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>8c5da76b-c283-455b-8520-be4238c785ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email' and @placeholder = 'name@email.com']</value>
      <webElementGuid>b88ff9bb-0d87-4c23-925f-09994ca3d2b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
