<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>00. 이벤트 카드 배너 버튼</name>
   <tag></tag>
   <elementGuidId>c44b5db2-9830-4ca5-895f-5d277f156d96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/main/section[2]/section/div/div/article/a/div/div[4]/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.flex-col.items-center.justify-end.space-y-6.pb-10.absolute.inset-x-0.bottom-0 > picture > img.w-full</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2bcda117-4d8c-43b3-9e2f-4cf7c1833a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>b1e74dfa-ed58-4be1-a8c6-a1c261287ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>110</value>
      <webElementGuid>f7d96e35-d58b-4339-93a1-58afd961461f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>83</value>
      <webElementGuid>589f66c7-68b7-43d2-8ec1-24dc0b83d3ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>4a04c444-b777-4d9f-9eb7-e9566fbd1f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>32fb602b-b158-46c3-aeaa-edc67d215c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full</value>
      <webElementGuid>264d807a-bcd2-4a6b-8e63-3e6641cda2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://story-a.tapas.io/prod/story/2024-11-01/2x/1d72270f-f748-4a9c-917c-aa64865cd060.png</value>
      <webElementGuid>2c7d9442-e083-4179-9d03-624331b39549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative mx-auto flex min-h-full flex-col text-base60 __variable_026074 __variable_3c0b91&quot;]/div[@class=&quot;mx-auto flex grow flex-col w-1010&quot;]/main[@class=&quot;flex flex-col items-center w-full space-y-4&quot;]/section[@class=&quot;flex flex-col items-center self-stretch w-full space-y-4&quot;]/section[@class=&quot;w-full&quot;]/div[@class=&quot;flex w-full flex-col space-y-4&quot;]/div[@class=&quot;flex w-full flex-wrap items-start scrollbar-hide gap-4 px-11 pc-card-list&quot;]/article[1]/a[1]/div[@class=&quot;flex w-full flex-col justify-between relative overflow-hidden rounded-8&quot;]/div[@class=&quot;flex flex-col items-center justify-end space-y-6 pb-10 absolute inset-x-0 bottom-0&quot;]/picture[1]/img[@class=&quot;w-full&quot;]</value>
      <webElementGuid>678a6e3a-c3cc-4dc0-95af-b8f20cf3e0a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/section[2]/section/div/div/article/a/div/div[4]/picture/img</value>
      <webElementGuid>821cf1f8-c2fe-4ba5-b505-a7205bb863d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://story-a.tapas.io/prod/story/2024-11-01/2x/1d72270f-f748-4a9c-917c-aa64865cd060.png')]</value>
      <webElementGuid>7a024e1e-cae3-46fa-b703-ae63fee62f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/picture/img</value>
      <webElementGuid>23a03e3f-b082-4c30-bf61-ee5b3f03a37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://story-a.tapas.io/prod/story/2024-11-01/2x/1d72270f-f748-4a9c-917c-aa64865cd060.png']</value>
      <webElementGuid>8ed04b2f-9ea9-49a8-812c-05762c408cfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
