<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>01.검색버튼</name>
   <tag></tag>
   <elementGuidId>08066403-da68-4014-957b-5dd7c399dabd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/nav/div/div/div/div/form/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a046cfc8-40a4-4d5e-a3e1-8675cc8ae3ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>3fe83bdd-3d71-4948-b579-40c87128a042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>fe25d6ce-a11d-4336-9eca-eb5d32388f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>2aa5ee93-4ddf-45c9-adff-ee946b8ca6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>79b952d8-d1d9-48b5-9ab1-8b0ce4f683da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>9cbf0c43-4876-40c9-aedb-1719c49f6511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7e2a0299-7fb8-43ca-8732-050c1880cf1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute right-2 top-2/4 -translate-y-2/4</value>
      <webElementGuid>24eda0d2-76ad-4472-a39b-b7bc9ad43dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static.tapas.io/7.8.0/resource/ic_24_navi_input_search.svg</value>
      <webElementGuid>e16a0273-fb7a-4b1a-a1e2-087fe3397836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative mx-auto flex min-h-full flex-col text-base60 __variable_a04e73 __variable_aa69c3&quot;]/nav[@class=&quot;sticky top-0 z-navigation w-full bg-bg10&quot;]/div[@class=&quot;mx-auto w-1010 bg-bg10&quot;]/div[1]/div[@class=&quot;relative bg-bg10 px-18 pb-20 pt-32&quot;]/div[@class=&quot;flex items-center justify-between space-x-20&quot;]/form[@class=&quot;relative inline-block&quot;]/button[1]/img[@class=&quot;absolute right-2 top-2/4 -translate-y-2/4&quot;]</value>
      <webElementGuid>ee86d9b1-5f0a-480d-802b-f88b0693a9f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/nav/div/div/div/div/form/button/img</value>
      <webElementGuid>f9d70f1a-a695-4589-a821-3322f2fcfd71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='search']</value>
      <webElementGuid>e37ebdf7-7c3f-499b-b2e0-ea38f06a431d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>57a4e093-a8fe-4e23-9179-fb140b9cb086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'search' and @src = 'https://static.tapas.io/7.8.0/resource/ic_24_navi_input_search.svg']</value>
      <webElementGuid>45ab3738-7351-478f-a25f-8b64518b841b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
