<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_More_absolute left-0 top-0 size-full rounded-100 border-1 border-888</name>
   <tag></tag>
   <elementGuidId>9cd6cbfa-0400-4f6c-af55-3f626f683bca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='headlessui-popover-button-:Rbraqcm:']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e967ec3b-22c8-458c-9008-3b9b711180d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute left-0 top-0 size-full rounded-100 border-1 border-[#888]</value>
      <webElementGuid>a262a3b1-6ace-4203-943f-c2c39c20dce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-popover-button-:Rbraqcm:&quot;)/div[@class=&quot;relative rounded-100&quot;]/div[@class=&quot;absolute left-0 top-0 size-full rounded-100 border-1 border-[#888]&quot;]</value>
      <webElementGuid>39d2de2f-ea78-4cea-8ed9-4e2b842ced5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='headlessui-popover-button-:Rbraqcm:']/div/div</value>
      <webElementGuid>74f23c43-7084-4efe-8c74-5f2366ee1161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/div/div</value>
      <webElementGuid>35ee4705-4d4d-4296-b390-02bdc9a5a8ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
