<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>05.검색썸네일</name>
   <tag></tag>
   <elementGuidId>3e3b5d4a-666b-454f-b8d5-f8598dadfd46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrap']/div/section/ul/li/div/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.thumb-overlay</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a233b142-f999-4b71-85e9-13de62b8476f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>thumb-overlay</value>
      <webElementGuid>49e55327-b4ca-4c78-80f1-93d162864984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrap&quot;)/div[@class=&quot;global-page&quot;]/section[@class=&quot;page-section&quot;]/ul[@class=&quot;content-list-wrap&quot;]/li[@class=&quot;search-item-wrap&quot;]/div[@class=&quot;item-thumb-wrap&quot;]/a[@class=&quot;thumb-wrap js-fb-tracking js-tiara-tracking&quot;]/div[@class=&quot;thumb-overlay&quot;]</value>
      <webElementGuid>e2d05ebb-ba19-47e3-91e9-b61d376c2ed3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrap']/div/section/ul/li/div/a/div</value>
      <webElementGuid>49ea0b2e-ee9e-4933-b6d7-9963ea0a112b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/a/div</value>
      <webElementGuid>c8f21f75-4c92-4f47-8e8b-c1cc3730122e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
