<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>06.검색작품섬네일</name>
   <tag></tag>
   <elementGuidId>02eec899-7ae5-492b-b7e8-c2da28e26faa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.thumb-overlay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrap']/div/section/ul/li/div/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>05acf693-4b07-4ae4-8a82-d9a6c6d6e5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>thumb-overlay</value>
      <webElementGuid>5a26374a-c842-4fa0-af15-e701f732d71f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrap&quot;)/div[@class=&quot;global-page&quot;]/section[@class=&quot;page-section&quot;]/ul[@class=&quot;content-list-wrap&quot;]/li[@class=&quot;search-item-wrap&quot;]/div[@class=&quot;item-thumb-wrap&quot;]/a[@class=&quot;thumb-wrap js-fb-tracking js-tiara-tracking&quot;]/div[@class=&quot;thumb-overlay&quot;]</value>
      <webElementGuid>fbd41293-9e5a-4baf-ae53-72fe953cfff6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrap']/div/section/ul/li/div/a/div</value>
      <webElementGuid>ae181f0d-6ff3-4c78-869b-52a7c4525e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/a/div</value>
      <webElementGuid>1d99780a-0464-4ebd-a286-2ddb158c2a1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
