<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>07.Novel탭</name>
   <tag></tag>
   <elementGuidId>c3b8d67f-47c6-4521-bdd2-44dca5640703</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.item-title.js-fb-tracking.js-search-novel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrap']/div/header/nav[2]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>69bacbc1-161c-4636-806a-2850a0fbc255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-title js-fb-tracking js-search-novel</value>
      <webElementGuid>29371082-3765-4292-953d-066e92f5d82e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fb-event</name>
      <type>Main</type>
      <value>screen_search</value>
      <webElementGuid>444153c3-9029-40c8-9f13-ae486679e272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>f02a9450-acd6-441d-9365-b4512e21df6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search?q=Soft%20Touch&amp;t=NOVELS</value>
      <webElementGuid>af9efa57-8f21-4cb0-8be4-9e2b8b1f4f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>novels</value>
      <webElementGuid>0b33c7f9-c275-4430-aea1-024b1057d2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrap&quot;)/div[@class=&quot;global-page&quot;]/header[@class=&quot;global-page-header&quot;]/nav[@class=&quot;section-filter&quot;]/ul[@class=&quot;filter-wrap&quot;]/li[@class=&quot;filter-item&quot;]/a[@class=&quot;item-title js-fb-tracking js-search-novel&quot;]</value>
      <webElementGuid>b0874f4c-3e2d-4a83-bdf1-fd5b22c95b67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrap']/div/header/nav[2]/ul/li[2]/a</value>
      <webElementGuid>65f0bb5f-9975-4f02-86ce-deae8835bd50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'novels')]</value>
      <webElementGuid>07985314-118d-45f4-9fae-4b444ecf252a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='comics'])[1]/following::a[1]</value>
      <webElementGuid>b1556800-c313-4935-8277-c54762386462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='search results'])[1]/following::a[3]</value>
      <webElementGuid>3265c177-ee91-457e-9957-4853c0975ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='people'])[1]/preceding::a[1]</value>
      <webElementGuid>70c493e1-0f08-42aa-a822-bf7e6de03442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tags'])[1]/preceding::a[2]</value>
      <webElementGuid>5336c73e-9b63-4633-8bad-f1a2afbf724a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='novels']/parent::*</value>
      <webElementGuid>6e5ffe80-4024-4164-9f82-55443db15936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search?q=Soft%20Touch&amp;t=NOVELS')]</value>
      <webElementGuid>e611a2e0-363e-4a69-bc75-ae5f374324fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav[2]/ul/li[2]/a</value>
      <webElementGuid>772b8653-8eaf-444c-b7a9-c9f9f0e8c1cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search?q=Soft%20Touch&amp;t=NOVELS' and (text() = 'novels' or . = 'novels')]</value>
      <webElementGuid>c0cc2173-5690-4f73-9836-7960a2bcce74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
