<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>07.구독버튼</name>
   <tag></tag>
   <elementGuidId>dcf3fd8b-de71-4862-bfee-4a471403d476</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.button.js-tiara-tracking.button--subscribe.js-subscribe-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrap']/div/div/div/section/div[2]/div[2]/div[2]/div[3]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c623437c-7b20-41bc-ab7c-0abe521c1bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button js-tiara-tracking button--subscribe js-subscribe-btn</value>
      <webElementGuid>48a896a9-a742-47a7-83b9-515ea1d6cd62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-permalink</name>
      <type>Main</type>
      <value>/series/the-dukes-family-is-not-my-problem/info</value>
      <webElementGuid>933ef8c9-0a1c-43c7-956e-53ac87b9ae1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-subscribe-cnt</name>
      <type>Main</type>
      <value>14849</value>
      <webElementGuid>97003b38-7087-4717-b211-a575d21cf984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-section</name>
      <type>Main</type>
      <value>content_home</value>
      <webElementGuid>7805f3ae-0ae3-46ac-8626-ba2398548b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-page</name>
      <type>Main</type>
      <value>content_home_episodes</value>
      <webElementGuid>a66072af-fb79-49c0-9dc7-eeb7d4e53301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-action-name</name>
      <type>Main</type>
      <value>subscribe_click</value>
      <webElementGuid>88295ec0-4b35-4fed-a729-fe612830bc78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-page-meta-id</name>
      <type>Main</type>
      <value>298705</value>
      <webElementGuid>f8ea7354-df75-4050-8fc7-ef873518ac98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-page-meta-type</name>
      <type>Main</type>
      <value>series_id</value>
      <webElementGuid>91e644a6-bf0f-4993-8039-c8f1286be6f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-event-meta-id</name>
      <type>Main</type>
      <value>298705</value>
      <webElementGuid>28aa9061-1fbe-4831-a5ee-6b03dbe015bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-event-meta-type</name>
      <type>Main</type>
      <value>series_id</value>
      <webElementGuid>d1fb51de-a8a7-4252-829e-4d7c6633d794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-event-meta-series</name>
      <type>Main</type>
      <value>The Duke's Family Is Not My Problem</value>
      <webElementGuid>1575dc61-c3be-4bce-a6a8-4627c6f24c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-event-meta-series-id</name>
      <type>Main</type>
      <value>298705</value>
      <webElementGuid>cec24365-0965-4bfb-9008-aaca5c848578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-click-layer1</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>67c1ecec-f642-4d63-91c1-065dc119d6e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-custom-props-user-action</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>5a57df44-d1aa-400d-93d2-b957f5ed4736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subscribe</value>
      <webElementGuid>820bd779-c6bb-4d0e-8dd9-69f940092c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrap&quot;)/div[@class=&quot;series-root&quot;]/div[@class=&quot;section-wrapper&quot;]/div[@class=&quot;section-sub-wrapper&quot;]/section[@class=&quot;section section--left&quot;]/div[@class=&quot;section__top&quot;]/div[@class=&quot;info info--bottom&quot;]/div[@class=&quot;info__right&quot;]/div[@class=&quot;button-wrapper&quot;]/a[@class=&quot;button js-tiara-tracking button--subscribe js-subscribe-btn&quot;]</value>
      <webElementGuid>55b09148-02df-44bd-98de-8d20dfd7bdae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrap']/div/div/div/section/div[2]/div[2]/div[2]/div[3]/a[2]</value>
      <webElementGuid>b2a41924-ed2f-4ee2-849e-6f1aa2209f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Subscribe')]</value>
      <webElementGuid>8da3ece5-d4de-4d13-9ea2-854889b83bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue Ep. 4'])[1]/following::a[1]</value>
      <webElementGuid>e05d16c4-fd10-45db-b26f-c8f209caf526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comic'])[1]/following::a[5]</value>
      <webElementGuid>4065f197-7eb5-48d1-9528-6e5969133caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Episodes'])[1]/preceding::a[3]</value>
      <webElementGuid>add18a08-5864-4d11-a5be-8fa847301a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details'])[1]/preceding::a[4]</value>
      <webElementGuid>47cd34b4-407c-41c5-afb8-f54b85c8db84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Subscribe']/parent::*</value>
      <webElementGuid>5b751be2-f8a4-4f48-a4ab-821ee2309bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/a[2]</value>
      <webElementGuid>feb214f4-4b2a-4200-a206-a261908b3787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Subscribe' or . = 'Subscribe')]</value>
      <webElementGuid>4993af67-5873-4a35-a93e-31504993da53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
