<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>09.비활성화버튼</name>
   <tag></tag>
   <elementGuidId>8eeeb258-5c0a-4895-a765-6a2cd7daf1eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.button.js-tiara-tracking.js-subscribe-btn.button--subscribed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrap']/div/div/div/section/div[2]/div[2]/div[2]/div[3]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bd03f097-945a-4e30-987a-f08f6de581eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button js-tiara-tracking js-subscribe-btn button--subscribed</value>
      <webElementGuid>d77bc0e5-90e5-489d-b6d9-814cb351c0e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-permalink</name>
      <type>Main</type>
      <value>/series/the-dukes-family-is-not-my-problem/info</value>
      <webElementGuid>c859ae0f-07e2-4576-a6fc-d8baf03cbbae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-subscribe-cnt</name>
      <type>Main</type>
      <value>14856</value>
      <webElementGuid>87096285-2bfc-4116-a6c5-61903f8edcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-section</name>
      <type>Main</type>
      <value>content_home</value>
      <webElementGuid>24480e25-9023-4e6a-b7bd-1a7091d7ec36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-page</name>
      <type>Main</type>
      <value>content_home_episodes</value>
      <webElementGuid>2a4e5033-abe4-4dc8-9f19-58da6bf6d363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-action-name</name>
      <type>Main</type>
      <value>subscribe_click</value>
      <webElementGuid>96a96714-8cde-401f-95c7-ef62ed0ba0f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-page-meta-id</name>
      <type>Main</type>
      <value>298705</value>
      <webElementGuid>74bbc689-24b4-4446-8f35-060a58d4a76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-page-meta-type</name>
      <type>Main</type>
      <value>series_id</value>
      <webElementGuid>c74d3e56-8e45-4b9b-8af3-ed94aced2291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-event-meta-id</name>
      <type>Main</type>
      <value>298705</value>
      <webElementGuid>69f6f7f9-57e8-4f33-a5bc-8ee557d136d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-event-meta-type</name>
      <type>Main</type>
      <value>series_id</value>
      <webElementGuid>0ace4fcc-1946-48eb-a932-4ce7e4cd09e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-event-meta-series</name>
      <type>Main</type>
      <value>The Duke's Family Is Not My Problem</value>
      <webElementGuid>68ef042d-5d9a-4e7d-b3ac-ae348cca8139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-event-meta-series-id</name>
      <type>Main</type>
      <value>298705</value>
      <webElementGuid>697d295d-1bfa-4af3-9080-5dd313a46970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-click-layer1</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>80ea54b0-417f-431b-b898-a1f6c95dfef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-custom-props-user-action</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>b751221a-7ed5-4f59-895b-d905f8e20108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subscribed</value>
      <webElementGuid>4a7c80cd-4e52-44c1-87cb-c42b24f311da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrap&quot;)/div[@class=&quot;series-root&quot;]/div[@class=&quot;section-wrapper&quot;]/div[@class=&quot;section-sub-wrapper&quot;]/section[@class=&quot;section section--left&quot;]/div[@class=&quot;section__top&quot;]/div[@class=&quot;info info--bottom&quot;]/div[@class=&quot;info__right&quot;]/div[@class=&quot;button-wrapper&quot;]/a[@class=&quot;button js-tiara-tracking js-subscribe-btn button--subscribed&quot;]</value>
      <webElementGuid>5cf4b490-4744-4f15-a0d1-5bf774e7a7a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrap']/div/div/div/section/div[2]/div[2]/div[2]/div[3]/a[2]</value>
      <webElementGuid>f1501546-b296-4217-ae20-e8d4923e8f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Subscribed')]</value>
      <webElementGuid>0f6fe54f-b8c2-41ab-8161-f91ec7979803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue Ep. 4'])[1]/following::a[1]</value>
      <webElementGuid>77ebf72f-d16f-4aa8-864e-14a6048c9d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comic'])[1]/following::a[5]</value>
      <webElementGuid>e92b2179-99b5-4b97-81de-103df7ac8569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Episodes'])[1]/preceding::a[3]</value>
      <webElementGuid>db7c0dfd-6197-4274-a127-e03a07f9579a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details'])[1]/preceding::a[4]</value>
      <webElementGuid>9381227f-93d5-4940-862f-de2ae928d453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Subscribed']/parent::*</value>
      <webElementGuid>9726c9e6-136c-4df9-86ba-576be31ccea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/a[2]</value>
      <webElementGuid>72afb956-d114-4ea3-85d8-295c65814961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Subscribed' or . = 'Subscribed')]</value>
      <webElementGuid>ed810bbc-e39d-437a-9e90-5d2819ce87a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
