<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>10.Unsubscribed토스트</name>
   <tag></tag>
   <elementGuidId>e501de57-cec4-4ba8-bdc7-a500f20bda12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#doneit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='doneit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>37eae328-bc26-45a0-a8df-86c8ed3b3304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>doneit</value>
      <webElementGuid>d060f39c-9059-4f8a-8fb9-a7fe765141db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>c17ff033-005e-4922-a8a0-2b2fde1d6277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unsubscribed</value>
      <webElementGuid>99e9c483-3f06-449c-a354-52cd75422305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;doneit&quot;)</value>
      <webElementGuid>9d40f93e-96fc-41a3-bbc0-71e804fc9fc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='doneit']</value>
      <webElementGuid>850a262b-0af7-4525-9dda-12c574b5b84f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue Ep. 4'])[2]/following::div[1]</value>
      <webElementGuid>33ad8860-0360-4b31-a6be-e0bf118430e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe'])[2]/following::div[1]</value>
      <webElementGuid>e555b7fc-ccac-4d42-98d5-64454b4d0728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Unsubscribed']/parent::*</value>
      <webElementGuid>3f3de8d9-2ad3-4da9-be21-b108491514ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]</value>
      <webElementGuid>ca1afbd8-beef-4d8c-a0cb-cbc9f74f8c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'doneit' and (text() = 'Unsubscribed' or . = 'Unsubscribed')]</value>
      <webElementGuid>57bb6dec-948c-4fae-80b8-97fa4d6ce417</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
