<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>11.이어보기버튼</name>
   <tag></tag>
   <elementGuidId>b33c0736-c913-4444-9f93-e9657c522ab7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.button.button--read.js-continue-btn.js-fb-tracking.js-tiara-tracking</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrap']/div/div/div/section/div[2]/div[2]/div[2]/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bebceb00-0a07-4c72-8ad3-eb9cd8f4330a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button--read js-continue-btn js-fb-tracking js-tiara-tracking</value>
      <webElementGuid>cd54b338-09c7-41e9-b28a-cbb040731c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fb-event</name>
      <type>Main</type>
      <value>screen_episode_comic</value>
      <webElementGuid>80da40ae-aa68-4cf5-b140-080a628fca8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>3449305</value>
      <webElementGuid>2309248b-b6b3-4377-9e25-47d2dccc7a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-section</name>
      <type>Main</type>
      <value>viewer</value>
      <webElementGuid>9b29964a-2ccf-43ac-a62e-a8bc51ab0f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-page</name>
      <type>Main</type>
      <value>viewer</value>
      <webElementGuid>cd8a89de-8220-4069-992b-8312de37faab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-action-name</name>
      <type>Main</type>
      <value>read_continue_click</value>
      <webElementGuid>684a2776-d354-4b64-8a4e-e95c8ac665ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-page-meta-id</name>
      <type>Main</type>
      <value>298705</value>
      <webElementGuid>827ed740-75a1-4bfd-bbfc-6dd175150888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-page-meta-type</name>
      <type>Main</type>
      <value>series_id</value>
      <webElementGuid>51ee891b-e592-4536-9991-b71223105d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-event-meta-id</name>
      <type>Main</type>
      <value>3449305</value>
      <webElementGuid>867ff523-1829-4007-b1d9-0aa2147ecdd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-event-meta-type</name>
      <type>Main</type>
      <value>episode_id</value>
      <webElementGuid>e165b08c-62b6-4200-8afa-e7723b60c233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-event-meta-series</name>
      <type>Main</type>
      <value>The Duke's Family Is Not My Problem</value>
      <webElementGuid>3c3b432f-e02b-4385-9e9e-3d07e8c507ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-event-meta-series-id</name>
      <type>Main</type>
      <value>298705</value>
      <webElementGuid>b6064b66-2171-44ef-a77c-bccea944526a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-click-layer1</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c1eef38a-7a09-4b1d-a737-d65c85f93927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tiara-custom-props-user-action</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>2025b2fa-ceee-4759-8f2a-334752da1325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/episode/3449305</value>
      <webElementGuid>477b28e1-a068-4612-9ed8-3750502314d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue Ep. 4</value>
      <webElementGuid>f0d81c8c-a461-482d-9a53-273d0ee7348f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrap&quot;)/div[@class=&quot;series-root&quot;]/div[@class=&quot;section-wrapper&quot;]/div[@class=&quot;section-sub-wrapper&quot;]/section[@class=&quot;section section--left&quot;]/div[@class=&quot;section__top&quot;]/div[@class=&quot;info info--bottom&quot;]/div[@class=&quot;info__right&quot;]/div[@class=&quot;button-wrapper&quot;]/a[@class=&quot;button button--read js-continue-btn js-fb-tracking js-tiara-tracking&quot;]</value>
      <webElementGuid>383461f8-bd4c-4e9c-9633-617eda5a5ffc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrap']/div/div/div/section/div[2]/div[2]/div[2]/div[3]/a</value>
      <webElementGuid>40099179-1dc6-4b7b-9ffb-d8532bf608a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Continue Ep. 4')]</value>
      <webElementGuid>6125615c-3ac5-4379-91a8-ae5f32435721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comic'])[1]/following::a[4]</value>
      <webElementGuid>5bfa42b4-717c-458c-97a2-65039224a78c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe'])[1]/preceding::a[1]</value>
      <webElementGuid>49c91ffc-11bd-49a2-9748-bb1c93d5b4e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Episodes'])[1]/preceding::a[4]</value>
      <webElementGuid>3d32c806-42ad-4f69-b5c5-1b4541fe4868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue Ep. 4']/parent::*</value>
      <webElementGuid>c1acf90a-d22b-4264-9432-392cebf63ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/episode/3449305')]</value>
      <webElementGuid>d1aecd08-afe4-4f85-ae4a-c8a467f18f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]/a</value>
      <webElementGuid>5068bd04-c14a-437e-ac99-bea7013f292a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/episode/3449305' and (text() = 'Continue Ep. 4' or . = 'Continue Ep. 4')]</value>
      <webElementGuid>8f6ea0fd-5508-451c-9edc-595787b91268</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
