<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>15.Details영역</name>
   <tag></tag>
   <elementGuidId>3c758926-a7d8-45ae-b9b7-27b3affce60d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrap']/div/div/div/section[2]/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e80dac8e-53e3-4ba7-bd4d-55dd35bd5955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row-header</value>
      <webElementGuid>3bed32f8-cd94-4785-95a2-4043385a59aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Details
                </value>
      <webElementGuid>fffdd75d-3887-4e4a-8ee5-a8edca769ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrap&quot;)/div[@class=&quot;series-root&quot;]/div[@class=&quot;section-wrapper&quot;]/div[@class=&quot;section-sub-wrapper&quot;]/section[@class=&quot;section section--right&quot;]/div[@class=&quot;section__row&quot;]/div[@class=&quot;row-header&quot;]</value>
      <webElementGuid>4d95900a-e780-405d-9e59-aced1cc7048a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrap']/div/div/div/section[2]/div[3]/div</value>
      <webElementGuid>f18f7dd6-e305-47ab-8d96-61e758bebaaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cha Sohee'])[3]/following::div[3]</value>
      <webElementGuid>ea1bdd74-5e41-4080-b8ce-3d943eeefc15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STUDIO INUS'])[3]/following::div[7]</value>
      <webElementGuid>d70b2b93-daad-47e6-863c-4c4bbdee436d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Updates every Sat'])[2]/preceding::div[1]</value>
      <webElementGuid>58cd9c0c-6b02-4c4f-9afa-d648d953cecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wait until Free Period is 1 day'])[2]/preceding::div[1]</value>
      <webElementGuid>df0eca3c-6393-4b28-932c-d11425ccafda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div[3]/div</value>
      <webElementGuid>bd4de7a5-f217-4b45-8f66-6be8782b0bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                    Details
                ' or . = '
                    Details
                ')]</value>
      <webElementGuid>b1809829-34e7-4305-baf8-60e384d8b90f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
