<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>18.로판장르버튼</name>
   <tag></tag>
   <elementGuidId>afe8397f-b76c-4bca-b834-dadc29a63f7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/div/div/div/div/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9316f03a-c3a4-46d9-8e86-1c5f1f8c61c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group relative mb-4 mr-12 inline-flex h-20 cursor-pointer whitespace-nowrap text-base30 font-system-14b hover:text-base60</value>
      <webElementGuid>dbe7fab2-67e0-43dd-b231-971777c43f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/static-landing/genre?category=COMIC&amp;bm=ALL&amp;sort=POPULAR&amp;genre=ROMANCE_FANTASY</value>
      <webElementGuid>1dd2356b-698e-4ed5-9074-96293071811e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Romance Fantasy</value>
      <webElementGuid>26102177-9d9e-474c-9464-d1e15501b64a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative mx-auto flex min-h-full flex-col text-base60 __variable_a04e73 __variable_aa69c3&quot;]/div[@class=&quot;mx-auto flex grow flex-col w-1010&quot;]/div[1]/div[@class=&quot;mb-20 mr-18 flex flex-col&quot;]/div[@class=&quot;flex justify-center&quot;]/div[@class=&quot;relative flex grow flex-col justify-center overflow-x-hidden&quot;]/div[1]/div[@class=&quot;relative&quot;]/div[@class=&quot;z-navigation flex w-full items-center overflow-x-scroll scrollbar-hide&quot;]/a[@class=&quot;group relative mb-4 mr-12 inline-flex h-20 cursor-pointer whitespace-nowrap text-base30 font-system-14b hover:text-base60&quot;]</value>
      <webElementGuid>152a5117-2a16-46d9-ac6c-b44933ba299d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div/div/div/div/a[2]</value>
      <webElementGuid>c029cd05-223d-409f-97fc-d2cd3f7a40ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Romance Fantasy')]</value>
      <webElementGuid>38a23575-f6dc-4c08-bd61-40c5cc332c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::a[1]</value>
      <webElementGuid>0a7f54bd-fd9c-4b0a-ba3b-12647d1049aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publish'])[1]/following::a[2]</value>
      <webElementGuid>599cbf5f-a489-4957-89ff-6b88eb4ea6c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Romance'])[1]/preceding::a[1]</value>
      <webElementGuid>a2bf7099-63ef-4e9c-9863-e8f468320f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drama'])[1]/preceding::a[2]</value>
      <webElementGuid>48c89e2f-43fd-42a7-bb87-91f5d721c036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Romance Fantasy']/parent::*</value>
      <webElementGuid>5ed054c8-c6bf-4291-a881-0f84436d43c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/static-landing/genre?category=COMIC&amp;bm=ALL&amp;sort=POPULAR&amp;genre=ROMANCE_FANTASY')]</value>
      <webElementGuid>0b1d347d-9cc8-460b-a098-bf9a805f564b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/a[2]</value>
      <webElementGuid>4da6d966-f939-412b-9e18-91ba72f87fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/static-landing/genre?category=COMIC&amp;bm=ALL&amp;sort=POPULAR&amp;genre=ROMANCE_FANTASY' and (text() = 'Romance Fantasy' or . = 'Romance Fantasy')]</value>
      <webElementGuid>6ab4efb0-7a9e-4dfe-9380-360cd21c56d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
