<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>04.빅배너이미지</name>
   <tag></tag>
   <elementGuidId>5cda7776-3809-439c-bb92-7bade87d3f57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.flex.flex-col.justify-end.items-start.space-y-10 > picture > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/main/section/section/div/div/div/div/div/article/a/div/div[2]/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e3d425e1-c3eb-42cc-85d8-0b5a1a38c0cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>d93345f9-bb0b-4863-adff-b75b4d4a2620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>6d9a6b84-94fc-4f6c-88c0-516a4410e59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>7304b574-86b1-4f60-9590-b72cc95e4599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>789ddd9e-e33e-4b8f-adb0-45c41ae8933e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>da7ce3a3-c488-41a9-a1cb-3ee2e54f053a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://story-a.tapas.io/prod/story/f62feccc-6c5c-4f59-88f0-2bbd12f96b11/t1/2x/t1_We_Hate_the_Male_Lead.png</value>
      <webElementGuid>e9c1405b-d560-4de0-ad5b-5a04e4faede7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative mx-auto flex min-h-full flex-col text-base60 __variable_a04e73 __variable_aa69c3&quot;]/div[@class=&quot;mx-auto flex grow flex-col w-1010&quot;]/main[@class=&quot;flex flex-col items-center w-full space-y-4&quot;]/section[@class=&quot;flex flex-col items-center self-stretch w-full space-y-4&quot;]/section[@class=&quot;w-full&quot;]/div[@class=&quot;px-11 flex w-full flex-col space-y-4&quot;]/div[@class=&quot;w-full rounded-16 relative overflow-hidden flex&quot;]/div[@class=&quot;swiper swiper-initialized swiper-horizontal !z-0 w-full swiper-backface-hidden&quot;]/div[@class=&quot;swiper-wrapper&quot;]/div[@class=&quot;swiper-slide swiper-slide-active&quot;]/article[1]/a[1]/div[@class=&quot;relative w-full flex-[1_0_100%] cursor-pointer&quot;]/div[@class=&quot;flex flex-col absolute bottom-0 left-0 space-y-10 items-start justify-center h-full w-432 pl-32&quot;]/div[@class=&quot;flex flex-col justify-end items-start space-y-10&quot;]/picture[1]/img[1]</value>
      <webElementGuid>3397d6ae-449b-4ee1-aee9-09719576da92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/section/section/div/div/div/div/div/article/a/div/div[2]/div/picture/img</value>
      <webElementGuid>2b69a9c4-26e1-4e21-b499-3726c063a2c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://story-a.tapas.io/prod/story/f62feccc-6c5c-4f59-88f0-2bbd12f96b11/t1/2x/t1_We_Hate_the_Male_Lead.png')]</value>
      <webElementGuid>234c9f11-7a7e-4ae5-90ca-950bfae5cd0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/picture/img</value>
      <webElementGuid>52b34e00-c16c-47b3-8a6b-0c921f87e387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://story-a.tapas.io/prod/story/f62feccc-6c5c-4f59-88f0-2bbd12f96b11/t1/2x/t1_We_Hate_the_Male_Lead.png']</value>
      <webElementGuid>2ff0734c-409d-4697-847f-4f3a6ec4831d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
