<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>08.작품이미지</name>
   <tag></tag>
   <elementGuidId>0b2cce20-26ab-4df5-9fde-85daeb640807</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.h-auto.w-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b23b22a4-6883-4905-9cbe-3047696c5dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>event-detail</value>
      <webElementGuid>a97dd6b9-d5bf-47f4-855b-0bb57b9f71a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>event-detail-image-0</value>
      <webElementGuid>16cd0c21-10ef-4172-aa0b-fa0d69369b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>c84569e5-a54f-49f9-8f5e-a3acc1dcb57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c67b02d1-f19b-467b-ad09-a6700a0d165f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>64cff8f6-b349-4dfe-9962-cd21a67fee83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>f7e37fc9-9984-4449-bc03-a696424ac454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e66e0181-6aaf-4730-8134-0483c495770a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-auto w-full</value>
      <webElementGuid>4584df86-2253-4149-8a4b-5e0e552ebe5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://story-a.tapas.io/prod/story/2025-02-05/2x/8c2fb800-aa5a-4f83-b017-0011038dbdd6.png</value>
      <webElementGuid>1382f9e5-7594-4f4c-bc14-c7597d12d096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative mx-auto flex min-h-full flex-col text-base60 __variable_a04e73 __variable_aa69c3&quot;]/div[@class=&quot;mx-auto flex grow flex-col w-1010&quot;]/div[@class=&quot;cursor-pointer&quot;]/picture[1]/img[@class=&quot;h-auto w-full&quot;]</value>
      <webElementGuid>15742b5f-2c71-44fa-841a-9405bb17ac3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/picture/img</value>
      <webElementGuid>13fd6b0d-525c-41cb-8ebc-ec748141336e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='event-detail']</value>
      <webElementGuid>2852cc58-2c71-4abc-8238-21c55f70874b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//picture/img</value>
      <webElementGuid>255a1c92-4803-4a39-8a77-0bef89d71c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'event-detail' and @src = 'https://story-a.tapas.io/prod/story/2025-02-05/2x/8c2fb800-aa5a-4f83-b017-0011038dbdd6.png']</value>
      <webElementGuid>09650dbf-9f8f-4b41-b9f5-f9d0b245427f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
