<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>02.첫번째작품</name>
   <tag></tag>
   <elementGuidId>b7ce6576-8e0d-4b9b-b65d-e8fc7bdf00c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.absolute.inset-0 > picture > img.size-full.object-cover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/main/section[2]/section/div/div/article/a/div/div[2]/div/div/div/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>34fd95af-1ebe-489f-877d-6cd2e2e8c902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>2d317fdd-745f-4e3a-8cf9-aed7d72f4207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>4183a307-1afa-4bc7-bf7a-5678d099d538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>66aeb179-2deb-44af-9cee-fd77aff190b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>a53eda85-f6aa-4f5e-bcde-9b5221838e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>27f49e3c-729d-4011-8b56-0bacf21efe22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>size-full object-cover</value>
      <webElementGuid>581b52c2-885e-4b2f-88e0-4e3882c9dd96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://story-a.tapas.io/prod/story/3c588cbd-6553-4efb-bd22-767516ab0e99/bc/2x/9abad2c4-02c7-4a97-a632-9578bceb92e8.png</value>
      <webElementGuid>22155370-6904-4b59-824b-7966f717f5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative mx-auto flex min-h-full flex-col text-base60 __variable_a04e73 __variable_aa69c3&quot;]/div[@class=&quot;mx-auto flex grow flex-col w-1010&quot;]/main[@class=&quot;flex flex-col items-center w-full space-y-4&quot;]/section[@class=&quot;flex flex-col items-center self-stretch w-full space-y-4&quot;]/section[@class=&quot;w-full&quot;]/div[@class=&quot;flex w-full flex-col space-y-4&quot;]/div[@class=&quot;flex w-full flex-wrap items-start scrollbar-hide gap-4 px-11 pc-card-list&quot;]/article[1]/a[1]/div[@class=&quot;relative overflow-hidden rounded-8&quot;]/div[@class=&quot;relative w-full&quot;]/div[@class=&quot;absolute inset-0 flex w-full flex-col justify-between&quot;]/div[@class=&quot;w-full px-10 pt-14&quot;]/div[@class=&quot;w-full relative overflow-hidden rounded-r-6 border border-solid border-t-black20 shadow-[8px_16px_30px_1px_rgba(0,0,0,0.40)]&quot;]/div[@class=&quot;absolute inset-0&quot;]/picture[1]/img[@class=&quot;size-full object-cover&quot;]</value>
      <webElementGuid>03a90430-2ec5-49f9-b6d1-cf553c719c9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/section[2]/section/div/div/article/a/div/div[2]/div/div/div/div/picture/img</value>
      <webElementGuid>95884908-2ad2-4248-b7ae-e039cdb6d429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://story-a.tapas.io/prod/story/3c588cbd-6553-4efb-bd22-767516ab0e99/bc/2x/9abad2c4-02c7-4a97-a632-9578bceb92e8.png')])[2]</value>
      <webElementGuid>bcabda8a-3f7e-4115-a657-181d534432e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/picture/img</value>
      <webElementGuid>03fb16e5-f314-4d5d-8398-6ac0af07aa02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://story-a.tapas.io/prod/story/3c588cbd-6553-4efb-bd22-767516ab0e99/bc/2x/9abad2c4-02c7-4a97-a632-9578bceb92e8.png']</value>
      <webElementGuid>e184b875-6b71-4191-b75c-f4ef2d733221</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
